### ISSUE TITLE
Docker fails: RuntimeError: Directory 'static/admin' does not exist

### ISSUE THREAD

**Issue by mape** [toverainc/willow-application-server#39]
I updated the docker image but encountered the following error:
```main: Pulling from toverainc/willow-application-server
a803e7c4b030: Pull complete
bf3336e84c8e: Pull complete
7fec366bd7fe: Pull complete
1a22e9af4e7a: Pull complete
b07e90d14538: Pull complete
49247b104341: Pull complete
c411a776a271: Pull complete
3dd5b7f85829: Pull complete
8712fb1a8a93: Pull complete
815eab127a81: Pull complete
8927b26d1746: Pull complete
1df8b8838e2d: Pull complete
6537347e282c: Pull complete
Digest: sha256:4bea69b6610b7af8429c1f83af7d57be8c0adad6bae1f63d110e78c75adb7069
Status: Downloaded newer image for ghcr.io/toverainc/willow-application-server:main
ghcr.io/toverainc/willow-application-server:main
4c923c444526b39bec7c11b9f636369237f88980f480345de1181e170008b051
Migrating legacy WAS client configuration...
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.12/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/api.py", line 206, in <module>
    app.mount("/admin", StaticFiles(directory="static/admin", html=True), name="admin")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/admin' does not exist```

**Comment by stintel** [comment]
You should use the latest tag as of now. Will update the documentation.

**Comment by kristiankielhofner** [comment]
Sorry about this, the documentation has been updated to reflect the new container tags (default to latest) as well as link to our new Discord for the community.
