### ISSUE TITLE
OTA update failing, can't find OTA_URL defined in .env file

### ISSUE THREAD

**Issue by nikito** [toverainc/willow-application-server#8]
I tried to push an OTA update via WAS and get this error:

2023-07-05T22:18:56] ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api.py", line 249, in post_ota
    msg = json.dumps({'cmd': 'ota_start', 'ota_url': os.environ['OTA_URL']})
                                                     ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'OTA_URL'
[2023-07-05T22:18:56] INFO:     127.0.0.1:55642 - 'GET /api/config HTTP/1.1' 200 OK
[2023-07-05T22:18:56] INFO:     127.0.0.1:55646 - 'GET /api/nvs HTTP/1.1' 200 OK
[2023-07-05T22:18:56] INFO:     127.0.0.1:55656 - 'GET /api/clients HTTP/1.1' 200 OK
[2023-07-05T22:18:56] INFO:     127.0.0.1:55660 - 'GET /api/clients HTTP/1.1' 200 OK

Seems it can't find OTA_URL even though it is defined in .env. This was previously working so not sure what could have changed.

**Comment by nikito** [comment]
Also with noting, this is on the feature branch, not main.

**Comment by nikito** [comment]
Closing as this is resolved by feature/ota_from_gh 😃
